### ISSUE TITLE
Переходы

### ISSUE THREAD

**Issue by Ser-Gen** [Ser-Gen/fieldAutosize#6]
Если добавить полю стиль

``` css
textarea {
    transition: .2s;
}
```
- поле перестанет сжиматься при удалении содержимого
- будет появляться полоса прокрутки при увеличении размера поля.
